{% set name = "rpy2" %}
{% set version = "3.6.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: rpy2
  version: {{ version }}

source:
  # the tag on github has the format RELEASE_x_x_x
  url: https://github.com/rpy2/rpy2/archive/refs/tags/RELEASE_{{ version.replace('.', '_') }}.tar.gz
  sha256: 241411d196e08f571c72904647018ef242df11ed5cd6c1fdcfcabf3e6ecbc645

build:
  number: 0

outputs:
  - name: {{ name|lower }}-rinterface
    script: build-rinterface.sh   # [unix]
    script: bld-rinterface.bat    # [win]
    build:
      rpaths:
        - lib/R/lib/
        - lib/
      run_exports:
        - {{ pin_subpackage("rpy2-rinterface", max_pin="x.x.x") }}
    requirements:
      build:
        - python
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - cffi                                # [build_platform != target_platform]
        - {{ stdlib("c") }}
        - {{ compiler('c') }}
        - {{ posix }}make
        - {{ posix }}base                  # [win]
        - liblzma-devel                    # [build_platform != target_platform]
        - zlib                             # [build_platform != target_platform]
      host:
        - python
        - setuptools
        - pip
        - r-base
        - cffi >=1.15.1
        - liblzma-devel
        - zlib
      run:
        - python
        - r-base
        - cffi >=1.15.1
        - packaging  # [win]
    test:
      source_files:
        - rpy2-rinterface/
      requires:
        - r-survival
        - pytest
      imports:
        - rpy2
        - rpy2.rlike
        # calls `get_rlib_path` and that only works for *nix
        - rpy2.rinterface       # [not win]
        - rpy2.rinterface_lib   # [not win]
      commands:
        - pytest -s -rxs -v rpy2-rinterface/
  - name: {{ name|lower }}-robjects
    script: build-robjects.sh   # [unix]
    script: bld-robjects.bat    # [win]
    build:
      run_exports:
        - {{ pin_subpackage("rpy2-robjects", max_pin="x.x.x") }}
    requirements:
      build:
        - python
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - {{ stdlib("c") }}
        - {{ compiler('c') }}
        - {{ posix }}make
        - {{ posix }}base                     # [win]
      host:
        - python
        - setuptools
        - pip
        - r-base
        - jinja2
        - tzlocal
        - {{ pin_subpackage("rpy2-rinterface", exact=True) }}
      run:
        - {{ pin_subpackage("rpy2-rinterface", exact=True) }}
        - python
        - r-base
        - jinja2
        - tzlocal
    test:
      source_files:
        - rpy2-robjects/
      requires:
        - r-cairo  # [not (aarch64 or ppc64le)]
        - r-ggplot2 >=2.2.1
        - ipython
        - numpy
        - pandas
        - pytest
      imports:
        - rpy2
        # calls `get_rlib_path` and that only works for *nix
        - rpy2.interactive   # [not win]
        - rpy2.ipython       # [not win]
        - rpy2.robjects      # [not win]
        - rpy2.robjects.lib  # [not win]
      commands:
        - pytest -s -rxs -v rpy2-robjects/ -k "not test_svg_plotting_args and not test_POSIXct_datetime_from_timestamp"  # [not (win or aarch64 or ppc64le)]
  - name: {{ name|lower }}
    build:
      noarch: generic
      skip: true  # [not linux64]
    requirements:
      run:
        - {{ pin_subpackage('rpy2-rinterface', max_pin="x.x.x") }}
        - {{ pin_subpackage('rpy2-robjects', max_pin="x.x.x") }}
    test:
      imports:
        - rpy2

about:
  home: https://github.com/rpy2/rpy2
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: gpl-2.0.txt
  summary: Python interface to the R language (embedded R)
  doc_url: https://rpy2.github.io/

extra:
  recipe-maintainers:
    - conda-forge/r
    - ceholden
    - ocefpaf
